name = "TrajectoryGamesBase"
uuid = "ac1ac542-73eb-4349-ae1b-660ab3609574"
authors = ["lassepe <lasse.peters@mailbox.org> and contributors"]
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
