name: CI
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        julia_version: ["1.7","1"]
    name: julia ${{ matrix.julia_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia_version }}
      - uses: julia-actions/cache@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@latest
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
